# docker-compose.yml - Composition of micro-services to run OpenDLV software.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-10-16

version: '2'

services:
    
#    odsupercomponent:
#        image: ${IMAGE}
#        network_mode: host
#        volumes:
#        - ${CONFIGPATH}:/opt/opendlv.data
#        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    selflocalization:
       image: orbubuntu:orbubuntuv0 #orbamd:orbamdv0
       network_mode: "host"
       ipc: host
       environment:
           - DISPLAY=$DISPLAY
       ulimits:
         memlock:
           soft: 44236800
           hard: 44236800
       volumes:
           - /home/somliga/MasterThesis/latest/kitti:/kitty
           - /home/somliga/MasterThesis/latest/images:/media  #Needs folder with images and an ORBvoc.txt "--Camera.rx=-0.0132397","--Camera.cv=0.021005","--Camera.rz=-0.00121284"
           - /tmp/.X11-unix:/tmp/.X11-unix
       command: "/tmp/opendlv-perception-vision-orbslam2-dest/bin/opendlv-perception-vision-orbslam2 --name=cam0 --width=2560 --height=720 --bpp=24 --cid=${CID} --cameraType=1 --vocFilePath=/media/ORBvoc.txt --Camera.fx=699.783 --Camera.fy=699.783 --Camera.cx=637.704 --Camera.cy=360.875 --Camera.k1=-0.173042 --Camera.k2=0.026726 --Camera.k3=0 --Camera.p1=0 --Camera.p2=0 --Camera.rx=-0.0132397 --Camera.cv=0.021005 --Camera.rz=-0.00121284 --Camera.baseline=0.12 --Camera.fps=15 --Camera.bf=84.027 --Camera.RGB=1 --ThDepth=45 --ORBextractor.nFeatures=2500 --ORBextractor.scaleFactor=1.2 --ORBextractor.nLevels=8 --ORBextractor.iniThFAST=12 --ORBextractor.minThFAST=3 --kittiPath=/kitty/dataset/sequences/parkinglot --refLatitude=47.000000 --refLongitude=11.00000 --startHeading=90"
#    vehicle_viewer:
#           image: testviewer
#           network_mode: host
#           ports:
#              - 8081:8081
#           command: "--cid=${CID}"
